apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: data-app
spec:
  containers:
    - name: nginx
      image: nginx123
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
